In [5]:
typeof(parse("123.323"))

Float64

In [6]:
typeof(parse(Int,"32 41"))

LoadError: ArgumentError: extra characters after whitespace in "32 41"

In [10]:
split("12 345 678")

3-element Array{SubString{String},1}:
 "12" 
 "345"
 "678"

In [17]:
function main()
    
    # 整数の入力
    a = parse(Int, "1")
    # スペース区切りの整数の入力
    (b, c) = map(x -> parse(Int, x), split("2 3"))
    # 文字列の入力
    s = "fffffff"
    # 出力
    print("$(a + b + c) $s")
    typeof((b, c))
end

main()

6 fffffff

Tuple{Int64,Int64}

In [30]:
function main()
    (a,b) = map(x -> parse(Int, x),split(readline()))
    if (a%2 == 0) || (b%2 ==0)
        println("Even")
    else
        println("Odd")    
    end
end
@time main()

STDIN> 10000 10000
Even
  2.485515 seconds (43.13 k allocations: 2.289 MiB)


In [29]:
function main()
    (a, b) = map(x -> parse(Int, x), split(readline()))
    c = a * b
    if c % 2 == 0
        println("Even")
    else
        println("Odd")
    end
end

@time main()

STDIN> 10000 10000
Even
  1.631735 seconds (43.08 k allocations: 2.290 MiB)


In [32]:
c = map(x -> parse(Int, x),split(readline()))

STDIN> 12 34


2-element Array{Int64,1}:
 12
 34

In [84]:
function main()
    if any(iseven.(parse.(Int,split(readline()))))
        println("Even")
    else
        println("Odd")
    end
end
main()

STDIN> 2345 99
Odd


In [36]:
parse.(split(readline()))

STDIN> 10000 100000


2-element Array{Int64,1}:
  10000
 100000

In [42]:
function main()
    a = count(c->c=='1', readline())
    println("$a")
end
main()

STDIN> 111
3


In [85]:
function main()
    N = readline()
    count = 0
    a = parse.(split(readline()))
    while all(iseven.(a))
        count += 1
        a=　div.(a,2)            
    end
    println("$count")
end
main()

STDIN> 16 16 16
STDIN> 16 16
4


In [13]:
N = parse.(Int,split(readline()))
N./ 2
String(N[2])

STDIN> 12 34 56


LoadError: MethodError: Cannot `convert` an object of type Int64 to an object of type String
This may have arisen from a call to the constructor String(...),
since type constructors fall back to convert methods.

In [61]:
all(iseven.([1,1.5]))

LoadError: MethodError: no method matching iseven(::Float64)
Closest candidates are:
  iseven(::Integer) at int.jl:68

In [77]:
Int64.([2 ;5; 4;]./2)

LoadError: InexactError()

In [87]:
"123456"[4]

'4': ASCII/Unicode U+0034 (category Nd: Number, decimal digit)

In [95]:
function main()
    a = parse(readline())
    b = parse(readline())
    c = parse(readline())
    x = parse(readline())
    count = 0
    for i in 0:a
        for j in 0:b
            for k in 0:c
                s = 500i + 100j + 50k
                if s == x 
                    count += 1
                end
            end
        end
    end
    println("$count")
end

main()

STDIN> 30
STDIN> 40
STDIN> 50
STDIN> 43
0


In [91]:
a = readline()

STDIN> 30


"30"

In [30]:
function main()
    #X = parse.(Int,split(readline()))
    #N = X[1]
    #A = X[2]
    #B = X[3]
    (N, A, B) = map(x -> parse(Int, x), split(readline()))
    cnt = 0
    kotae = 0
    for i in 1:N
        ketasum = 0
        imoji = "$i" 
        for j in 1:length(imoji)
            #iの各桁を数値へ変換して足す
            ketasum = ketasum + parse(Int,imoji[j])
        end
        if A <= ketasum <= B
            kotae = kotae + i
        end
    end
    println("$kotae")
end

main()

STDIN> 100 4 16
4554


In [82]:
function main()
    N = parse(Int,readline())
    a = map(x -> parse(Int,x), split(readline()))
    sort!(a,rev = true)
    Alice = 0
    Bob = 0
    for i in 1:N
        if isodd(i)
            Alice += a[i]
        else
            Bob += a[i]
        end
    end
    
    println("$(Alice - Bob)")
end

main()

STDIN> 4
STDIN> 20 18 2 18
18


In [18]:
length()

LoadError: MethodError: no method matching getindex(::Int64, ::UnitRange{Int64})

In [21]:
1:1

1:1

In [90]:
s = Set{Int}()
push!(s,4)
push!(s,5)

Set([4, 5])

In [93]:
function main()
    N = parse(Int,readline())
    a = Set{Int}()
    for i in 1:N
        push!(a,parse(Int,readline()))
    end
    
    println("$(length(a))")
end

main()

STDIN> 7
STDIN> 50
STDIN> 30
STDIN> 50
STDIN> 100
STDIN> 50
STDIN> 80
STDIN> 30
4


In [94]:
function main()
    N = parse(Int, readline())
    d = zeros(Int, (N,))
    for i = 1:N 
        d[i] = parse(Int, readline())
    end

    num = zeros(Int, (100,))
    for i = 1:N 
        num[d[i]] += 1
    end

    res = 0
    for i = 1:100
        if num[i] > 0
            res += 1
        end
    end

    println(res)
end

main()

STDIN> 2
STDIN> 1
STDIN> 1
1


In [110]:
function main()
    (N,Y) = map(x -> parse(Int,x),split(readline()))    
    noguchi = -1
    higuchi = -1
    fukuzawa = -1
    for numfuk in N:-1:0
        for numhig in N-numfuk:-1:0
            numnog = N - numfuk - numhig
            otoshi = 10000numfuk + 5000numhig + 1000numnog
            if Y == otoshi
                noguchi = numnog
                higuchi = numhig
                fukuzawa = numfuk
                #println("$fukuzawa $higuchi $noguchi")
            end
        end
    end

        println("$fukuzawa $higuchi $noguchi")
end

main()

STDIN> 1000 1234000
26 0 974
22 9 969
18 18 964
14 27 959
10 36 954
6 45 949
2 54 944
2 54 944


In [38]:
function main()
    divide = ["dream","dreamer","erase","eraser"]
    S = chomp(readline())
    Slen = length(S)
    ans = true
    while Slen > 0
        is_contains = false
        for i in 1:4
            if length(divide[i]) <= Slen
                if S[Slen - length(divide[i]) + 1: Slen] == divide[i]
                    is_contains = true
                    Slen -= length(divide[i])
                end
            end
        end
        
        if !is_contains
            ans = false
            break
        end
        
    end
    
    if ans
        println("YES")
    else
        println("NO")
    end
end

main()

STDIN> dreamdreameraserase
NO


In [16]:
i = 2
a = "abcd"
a[i:(i+1)]
"abc" == a[1:3]

true

In [17]:
T =""
T = T * "dream"

"dream"

In [19]:
a = "abc"
println(a)

abc


In [23]:
function main()
    divide = ["dream", "dreamer", "erase", "eraser"]

    S = chomp(readline())

    ans = true
    lenS = length(S)
    while lenS > 0
        is_contains = false
        for i = 1:4
            if length(divide[i]) <= lenS
                if S[lenS - length(divide[i]) + 1:lenS] == divide[i]
                    is_contains = true
                    lenS -= length(divide[i])
                end
            end
        end

        if !is_contains
            ans = false
            break
        end
    end

    if ans
        println("YES")
    else
        println("NO")
    end
end

main()

STDIN> dream
YES


In [46]:
function main()
    N = parse(Int,readline())
    t = zeros(Int , N +1)
    x = zeros(Int , N +1)
    y = zeros(Int , N +1)

    for i in 2:N+1
        (t[i] ,x[i] ,y[i]) = map(x -> parse(Int,x) , split(readline()))
    end
    
    can = true
    for i in 1:N
        dt = t[i + 1] - t[i]
        dist = abs(x[i + 1] - x[i]) + abs(y[i+ 1] - y[i])
        if dt < dist
            can = false
        end
        
        if dist%2 != dt%2
            can =false
        end
        
    end
    
    if can
        println("Yes")
    else
        println("No")
    end
    
end

main()

STDIN> 2
STDIN> 3 1 2
STDIN> 6 1 1
YES


In [9]:
function main()
    (r,g,b) = split(readline())
    num = parse(Int,r * g * b)
    
    if num % 4 == 0
        println("YES")
    else
        println("NO")
    end
        
end

main()

STDIN> 9 9 6
YES


In [4]:
(r,g,b) = split(readline())
parse(Int,r * g * b)

STDIN> 1 2 3


123